### ISSUE TITLE
Unable to add plugin to cordova app

### ISSUE THREAD

**Issue by vishnuprasad7** [IOCare/cordova-plugin-smartconfig#2]
Error: Failed to fetch plugin https://github.com/IOCare/cordova-plugin-smartconfig via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: Invalid character in entity name
Line: 5
Column: 67
Char:

**Comment by bkrajendra** [comment]
Thanks for reporting. Fixed it.
