### ISSUE TITLE
After the intelligent configuration is stopped normally, starting the smart configuration again will cause the app to crash.

### ISSUE THREAD

**Issue by angelofan** [IOCare/cordova-plugin-smartconfig#4]
After starting the smart config, stop the config before getting the callback, The app will crash.

I compared the latest code of github on Esp 8266 and found that one of its files has changed. Because my project is more urgent, I cloned your project to handle this problem, submitted it to my repository, and it works fine now. You can view and update your code against the change record. It just modified the code of about 4 lines in a file.

my github:
https://github.com/13546777510/cordova-plugin-smartconfig

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by bkrajendra** [comment]
Yes.. Im also tracking other plugin at https://github.com/coloz/cordova-plugin-esptouch
Will do changes after compiling all latest updates.

**Comment by angelofan** [comment]
@bkrajendra well, good luck!
