### ISSUE TITLE
Can not build in Xcode 

### ISSUE THREAD

**Issue by TruongHaiDang** [IOCare/cordova-plugin-smartconfig#7]
I have an ionic project and build with capacitor. When I integrate this plugin I get these error when build in Xcode:

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_ESPTouchTask

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_ESP_NetUtil

Every think working normally in android studio. Does anyone can help me?
Thanks a lot.

**Comment by ashishradadia** [comment]
same issue. is there any solution ?.

**Comment by bkrajendra** [comment]
Currently, I am not working on this plugin. 
I request to search for other alternatives.

**Comment by TruongHaiDang** [comment]
> same issue. is there any solution ?.

I gave up.
